### ISSUE TITLE
更新 app store 隐私政策网址

### ISSUE THREAD

**Issue by UNIDY2002** [thu-info-community/thu-info-app#267]

**Comment by Ashitemaru** [comment]
已经修改至https://thuinfo.net/privacy

**Comment by 84634E1A607A** [comment]
看上去又要改了, https://app.cs.tsinghua.edu.cn/privacy

**Comment by UNIDY2002** [comment]
这件事需要谨慎考虑，如果审核看到我们的隐私政策是个隶属于学校的网站，开发者却不是学校，审核会怎么想？

**Comment by 84634E1A607A** [comment]
现在 301 跳转不也差不多嘛 (x
