### ISSUE TITLE
Please add v3.0.0 to GitHub release

### ISSUE THREAD

**Issue by YuruiHong** [thu-info-community/thu-info-app#314]
I noticed that version 3.0.0 is available via WeChat official account. Please forward the release here and to the Tuna mirror if it is still an open source project.

**Comment by 84634E1A607A** [comment]
That is still a beta version. If you want the latest version, go to [github actions](https://github.com/UNIDY2002/THUInfo/actions) and download android artifact there. IOS builds are not yet possible.

**Comment by 84634E1A607A** [comment]
An example artifact is at https://github.com/UNIDY2002/THUInfo/suites/9034278504/artifacts/417169173

**Comment by Ashitemaru** [comment]
The iOS CI seems not working properly recently due to expired profiles. I am trying to fix it, but it is harder than I have thought.

**Comment by 84634E1A607A** [comment]
I think this issue can be closed.

**Comment by UNIDY2002** [comment]
> I think this issue can be closed.

FYI, the problem regarding iOS CI is still unsolved. (I simply removed the steps that caused the failure, but it didn't solve the problem.)

I will close this issue when v3 is released.
