### ISSUE TITLE
假期的教室资源显示

### ISSUE THREAD

**Issue by ouuan** [thu-info-community/thu-info-app#343]
**Describe the bug**

今天（2023.2.12）我使用 THUInfo 查看教室资源时，显示的是“第5周 周日”，并且和官网上查到的不一致。而且貌似只能选择查询第 1 周到第 18 周的教室资源信息，不包含假期？

**To Reproduce**
1. 打开 THUInfo 的“教室资源”
2. 选择三教

**Expected behavior**

显示当天的教室资源信息，最好是附带上日期，而不是只有周数和星期。

**Screenshots**

![THUInfo](https://user-images.githubusercontent.com/30581822/218293574-7333c071-bb09-4ddc-adaf-6164732e5b0e.png)

![官网](https://user-images.githubusercontent.com/30581822/218293586-1475b2f9-7732-4a1c-952f-b610ad7f7d4f.png)

**Version**

v2.6.7

**Device**

Redmi Note 10 Pro, MIUI 12.5.16

**Comment by UNIDY2002** [comment]
是的，我们在 3.0.0-beta 版尝试修复了周数错误的问题，可以试试：https://cloud.tsinghua.edu.cn/f/66a3f2815a2c41309e68/

包含假期周以及显示日期都是很好的建议，之后可能会考虑。

感谢反馈！

**Comment by ouuan** [comment]
> 是的，我们在 3.0.0-beta 版尝试修复了周数错误的问题，可以试试：[cloud.tsinghua.edu.cn/f/66a3f2815a2c41309e68](https://cloud.tsinghua.edu.cn/f/66a3f2815a2c41309e68/)

这个版本查到的确实是正确的了。只不过我暂时感觉原来的配色更好，可能是没习惯倒也还好，但为什么要不区分有课和借用，并且不显示图例呢 🤔

**Comment by UNIDY2002** [comment]
> 但为什么要不区分有课和借用，并且不显示图例呢

考虑找空教室这一常见场景，有课和借用的差异可能不是那么重要。「清华大学信息服务」→「学习与教务」→「公共信息」→「教室信息」也采用了双色模式（尽管和我们的配色恰好相反。。）。

关于图例，我们最后做了折衷，点击某个色块即可以悬浮框的形式看到该教室当前时段的具体情况。

**Comment by ouuan** [comment]
1. 和 v2 以及官网相反的配色可能会造成困惑 🤔
2. 不同占用原因的差异确实不重要，但也不是完全一点用都没有，如果显示差异没什么坏处的话为什么不显示呢。例如，随便猜几个有一点用的场景（我自己倒是无所谓，只是随便编一些场景，但其他用户可能真的有意想不到的需求）：有课一般是每周几乎一样的，但借用是临时的，可以借此规划时间；可以看一看大家喜欢借哪个教室，借此安排自己以后借哪个教室（也借大家喜欢的教室 / 避开大家喜欢的教室）。我猜不显示差异是为了 app 整体的配色是紫色？也可以问一下其他用户的想法，我是感觉保持整体都是紫色没必要。

之前有在公开的地方讨论吗，还是只有在群里讨论或者没有讨论？

**Comment by UNIDY2002** [comment]
> 之前有在公开的地方讨论吗，还是只有在群里讨论或者没有讨论？

没有在公开场合讨论，是开发团队内部决定的结果。

cc @JohnnyBGoodeLithium

**Comment by UNIDY2002** [comment]
关于教室资源配色，如果一段时间内没有回应，我将改为与官网一致的形式。
@ouuan @JohnnyBGoodeLithium

**Comment by ouuan** [comment]
> 关于教室资源配色，如果一段时间内没有回应，我将改为与官网一致的形式。

官网是指 https://zhjw.cic.tsinghua.edu.cn/pk.classroomctrl.do 还是清华大学信息服务？

**Comment by UNIDY2002** [comment]
@ouuan 前者

**Comment by ouuan** [comment]
和官网一致也挺好，只不过我感觉官网的“有课”对比度有点低 🤔 或许可以稍微调深一点，或者用回 THUInfo v2 的配色

**Comment by JohnnyBGoodeLithium** [comment]
> 1. 和 v2 以及官网相反的配色可能会造成困惑 🤔
> 2. 不同占用原因的差异确实不重要，但也不是完全一点用都没有，如果显示差异没什么坏处的话为什么不显示呢。例如，随便猜几个有一点用的场景（我自己倒是无所谓，只是随便编一些场景，但其他用户可能真的有意想不到的需求）：有课一般是每周几乎一样的，但借用是临时的，可以借此规划时间；可以看一看大家喜欢借哪个教室，借此安排自己以后借哪个教室（也借大家喜欢的教室 / 避开大家喜欢的教室）。我猜不显示差异是为了 app 整体的配色是紫色？也可以问一下其他用户的想法，我是感觉保持整体都是紫色没必要。
> 3. 图例主要是考虑到第一点说的，我倒是发现了有 tooltip，但应该会有很多人不能第一时间发现。
> 
> 之前有在公开的地方讨论吗，还是只有在群里讨论或者没有讨论？

1. 同意对于配色与官网相反的困惑问题，配色应修改为与用户习惯（官网情况）一致或相近；
2. 已占用教室的占用原因信息表现形式将做进一步设计，今天更新到设计稿中。

**Comment by UNIDY2002** [comment]
关闭了这个议题，因为这个议题指出的缺少假期周以及缺少日期显示的问题已经解决。
另，已反转教室状态配色(https://github.com/thu-info-community/thu-info-app/commit/ef354615c11b02a3170b606ceeedc2a455da025b)
