### ISSUE TITLE
WHY BANNING ROOTED DEVICES?

### ISSUE THREAD

**Issue by YuruiHong** [thu-info-community/thu-info-app#349]
**Describe the bug**
The app prohibits me from using it on an rooted Android device.

**To Reproduce**
1. Install the latest version via either the prompted link in the beta version or this repo.
2. Tap on the icon to attempt to open the app
3. Get prompted "禁止在Root设备上运行", which translates to "Running on rooted devices prohibited", and it continues until one manually ends the process.

**Expected behavior**
Remove the forced verification of the device, or give certain reasons for the decision.

**Screenshots**

**Version**
3.0.0

**Device**
Redmi K30i 5G (rooted)

**Additional context**
The testing versions of this app used to work fine on the same device.

**Comment by UNIDY2002** [comment]
Please try the second APK in the release: [THUInfo_release_v3.0.0_root_ye_neng_yong.apk](https://github.com/thu-info-community/thu-info-app/releases/download/v3.0.0/THUInfo_release_v3.0.0_root_ye_neng_yong.apk)

**Comment by UNIDY2002** [comment]
If the other APK still does not work, then I may have made a mistake. Please inform me and I will update the assets.

**Comment by YuruiHong** [comment]
Sorry that I failed to notice that "root ye neng yong" in the package name suggests that it is intended for rooted devices.🤣  I'll close this issue.
