### ISSUE TITLE
洗衣机适配 | 红衫

### ISSUE THREAD

**Issue by YiHui-Liu** [thu-info-community/thu-info-app#429]
增加对红衫宿舍的洗衣机、烘干机和洗鞋机的状态显示

**Comment by 84634E1A607A** [comment]
thu-info-app 没有写这一块哦, 宿舍洗衣机的情况是使用的 stevenlele 开发的洗衣机查询网页, 进行了 CSS 覆写. 拜托您通过洗衣机查询页的反馈渠道进行反馈, 谢谢~

**Comment by YiHui-Liu** [comment]
好的，谢谢
