### ISSUE TITLE
适配 OpenHarmony

### ISSUE THREAD

**Issue by CTCS5** [thu-info-community/thu-info-app#439]
不然系统根本不给安装apk
:3

**Comment by UNIDY2002** [comment]
对了，learnX 有这个问题么

**Comment by 84634E1A607A** [comment]
事实证明备案上架了也不行, 必须上架华为的应用市场. 近期暂不考虑这件事

**Comment by 84634E1A607A** [comment]
等 ReactNative 适配 HarmonyOS Next 和 OpenHarmony 之后可以考虑上架华为应用市场

**Comment by UNIDY2002** [comment]
参考：https://github.com/facebook/react-native/issues/45093

**Comment by UNIDY2002** [comment]
该议题长期不活跃，已关闭。如需帮助，请完善问题描述后再次创建议题。
