### ISSUE TITLE
洗衣机界面新UI

### ISSUE THREAD

**Issue by gtxzsxxk** [thu-info-community/thu-info-app#442]
URL：https://washer.tsinghuaiot.top/
仓库地址：https://github.com/gtxzsxxk/laundryservice-thu

这个是我一年前做的，自用一年，十分稳定。UI界面仿照的谷歌风格做的，和新info的界面应该比较切合，后端也是自己开发的接口，可以直接移植。希望能够贡献info，谢谢~

**Comment by 84634E1A607A** [comment]
非常感谢您的贡献！THU Info 有深色和浅色两种模式。如果有需求，我们 *可以* 利用您的后端自行搭建前端，获得更接近原生的体验。目前某智能校园洗衣机查询功能缺乏维护，部分数据不正确，我个人认为维护当前功能即可 （如紫荆一号楼2楼应该有5台洗衣机但是数据里只有3台；新的学生公寓没有在list中出现等）。 (当然这不代表最终意见)

**Comment by gtxzsxxk** [comment]
其实我的意思是贡献这个h5写的UI界面，这个界面支持两种模式的颜色切换，也暴露了填充数据的接口，但是感觉你们似乎不太感冒这个UI界面，难道因为你们的UI是原生的，所以不好移植吗？

**Comment by 84634E1A607A** [comment]
我们的UI目前是在https://washer.sdevs.top/的基础上覆写了它的CSS。我没有找到在哪里切换颜色 QaQ。

我的考虑部分包含了类似 https://github.com/thu-info-community/thu-info-app/issues/429 ， 即用户会向我们反馈数据问题，这可能会为您带来额外的工作量和麻烦。 您可以稍等， 待 UNIDY 有时间了在此进行探讨。

**Comment by gtxzsxxk** [comment]
> 我没有找到在哪里切换颜色

这个是自动跟随系统设置的

> 我们的UI目前是在 https://washer.sdevs.top/ 的基础上覆写了它的CSS

我这个也是参考了他的，但我的工作主要是重新写了个前端的页面，优化了一下界面。

> 我的考虑部分包含了类似 https://github.com/thu-info-community/thu-info-app/issues/429 ， 即用户会向我们反馈数据问题，这可能会为您带来额外的工作量和麻烦。 您可以稍等， 待 UNIDY 有时间了在此进行探讨。

好滴~谢谢回复

**Comment by UNIDY2002** [comment]
可以考虑这件事

**Comment by UNIDY2002** [comment]
请阐释一下，在 APP 中使用你的 h5 页面相比于 APP 直接访问智慧校园接口的优势。
为了保证接近原生的体验，我们会尽可能让 APP 中大多数功能都采用原生 UI 实现。

**Comment by gtxzsxxk** [comment]
谢谢回复～我的意思是，我只是做了一个UI界面，想贡献这个UI设计给THUINFO，至于h5的话，你们现在的实现不也是用h5改了几个css做的嘛

**Comment by UNIDY2002** [comment]
事实上，最初直接引入 stevenlele 的 h5 页面主要是由于当时人手和工作精力有限。在开发人手和精力充足的情况下，我们还是会尽可能考虑更贴近原生的解决方案，因此我才会提出上述问题。

**Comment by gtxzsxxk** [comment]
我觉得可能唯一的优势就是有一个似乎看起来google一点的ui界面吧，性能之类的我觉得肯定比不过原生。

谢谢回复～

**Comment by UNIDY2002** [comment]
非常感谢你的贡献！我也认可你的 UI 在交互设计上的优点。
另一方面，我们也在评估直接在 APP 内调用智慧校园 API 的可行性与工作量。如果实现原生功能可行，我们可能会自己实现一个原生的洗衣机查询功能；如果不可行，我们会采用你的新 UI。
再次感谢你对 THU Info 的关注！

**Comment by gtxzsxxk** [comment]
谢谢回复~其实我个人最支持你们直接在app内调用api并且实现原生页面，这样性能和外观都可以得到提升。还是感谢你们的工作~

**Comment by 84634E1A607A** [comment]
正在写新UI, 本 issue 先放在这, 我们将参考您的 UI 设计.
