### ISSUE TITLE
已同步到系统日历的课程不定期被删除

### ISSUE THREAD

**Issue by YuruiHong** [thu-info-community/thu-info-app#473]
**Describe the bug**
使用课表同步功能同步到系统日历的课程不定期被全部删除，不确定产生时机，也不确定是否由THUInfo本身导致。日历应用是Lineage OS系统自带的。

**Version**
3.4.4

**Device**
Lineage OS (Android 13) on Redmi K30i 5G

**Comment by UNIDY2002** [comment]
您要找的是不是：learnX

据我所知，THU Info 没有涉及日历的逻辑。
