### ISSUE TITLE
无法使用校园卡支付功能：You have aready made a deposite但应用未唤起

### ISSUE THREAD

**Issue by YuruiHong** [thu-info-community/thu-info-app#516]
**Describe the bug**
充校园卡使用微信选项，选择金额后提交，没有唤起微信（我的理解是需要唤起相应应用），支付不成功，此后再次尝试充值时弹出You have aready made a deposite开头的对话框，无法提交新的充值请求。因为卡在此处，尚不清楚银行卡/支付宝选项是否会出现相同问题。

Version
3.4.5

Device
Lineage OS 20 (Android 13) on Redmi K30i 5G

**Comment by UNIDY2002** [comment]
请确认您通过手机浏览器使用网页版（https://card.tsinghua.edu.cn/cardRecharge）能否唤起微信支付
