### ISSUE TITLE
校园卡充值金额最低门槛/分度值与网页/小程序不一致

### ISSUE THREAD

**Issue by YuruiHong** [thu-info-community/thu-info-app#518]
**Describe the bug**
在thuinfo中目前无法充值恰好10元，也无法充值任意非整数的金额，而其他各官方入口可以，可能是边界检查有误。

另外，当前判断是否重复充值的交互个人认为过于谨慎，现在是只要成功提交一次请求，拉起对应应用，后续再充值均弹出警告，而事实上有可能出现在外部应用支付界面取消的情况。建议可以修改提示内容。

**Comment by UNIDY2002** [comment]
感谢指出。这并非边界检查有误，而是学校端修改了检查条件。一个证据是，https://card.tsinghua.edu.cn/js/i18njs.js 中相应的 i18n 字段名称为 `inputtxamtgreater10`，说明曾经的边界条件确为大于 10 元。APP 后续会加以修改。

至于重复充值的交互，我认为谨慎是必要的。
