### ISSUE TITLE
使用规则推测夏季学期周数

### ISSUE THREAD

**Issue by UNIDY2002** [thu-info-community/thu-info-app#546]
每学期周数未知令我们经常收到无法解决的反馈。幸而在已知春季学期第一天的情况下，结合农历，我们就可以准确地推知夏季学期周数。规则如下：
- 若夏季学期所在农历年有闰月，则夏季学期共有 12 周；
- 若夏季学期所在农历年无闰月，则下一年春节应落在夏季学期结束后第 139~145 天，可反推出夏季学期的周数。

除此之外，我们还需调整课表的预取策略，并妥善处理周数不能被 3 整除的情况。

我认为这么做的成本低于让学校加接口。

**Comment by 84634E1A607A** [comment]
感觉不如让学校加接口

**Comment by UNIDY2002** [comment]
> 一年一个特例谁顶得住啊

夏季学期周数 10 年来还真没特例（

如果加接口，我们需要的其实是“下一个学期有几周”这样的接口，还是挺诡异的

**Comment by 84634E1A607A** [comment]
不如来个json版校历

**Comment by AsakuraMizu** [comment]
> 如果加接口，我们需要的其实是“下一个学期有几周”这样的接口，还是挺诡异的
> 
> 不过倒也不重要，如果能有“这一学期有几周”这样的接口，那也已经很好了

网络学堂实际上有这样的接口，路径为 https://learn.tsinghua.edu.cn/b/kc/zhjw_v_code_xnxq/getCurrentAndNextSemester

返回内容如下：
```json
{
  "result": {
    "xnxq": "2023-2024-3",
    "xnxqmc": "2023-2024夏季学期",
    "kssj": "2024-06-29",
    "jssj": "2024-09-06",
    "id": "2023-2024-3"
  },
  "message": "success",
  "resultList": [
    {
      "xnxq": "2024-2025-1",
      "xnxqmc": "2024-2025秋季学期",
      "kssj": "2024-09-07",
      "jssj": "2025-02-14",
      "id": "2024-2025-1"
    }
  ]
}
```
调用方法可以参考 https://github.com/Harry-Chen/thu-learn-lib/blob/1a9049602dbf41b622977e05e15e5c599f83f030/src/index.ts#L271
