### ISSUE TITLE
[Help wanted] Adapt to the new login API of id.tsinghua.edu.cn

### ISSUE THREAD

**Issue by SphenHe** [thu-info-community/thu-info-app#573]
**Describe the bug**
Unable to log in thuinfo. With error message:
```log
LoginError: Unexpected response status code: 500 (check)
```

**To Reproduce**
1. Enter the right id and password
2. Click the Login botton

**Expected behavior**
Successful auto-login like yesterday

**Screenshots**
![Screenshots of login page](https://github.com/thu-info-community/thu-info-app/assets/57851723/5f0b4739-20d0-4143-ae16-a4c8e02b6f93)

**Version**
3.6.4

**Device**
Redmi K50 - Xiaomi HyperOS 1.0.6.0.ULNCNXM

**Additional context**
Presumably related to the update of [id.tsinghua.edu.cn](id.tsinghua.edu.cn)

**Comment by 84634E1A607A** [comment]
我们已经收到了超过 50 份反馈 (乐), 学校于 7.6 对统一认证系统引入了 SM2 加密, 因此 THU Info App 的登录模块出现了功能异常.

但是开发者这两天都挺忙的, 我们争取尽快修复这个问题并发布更新.
