### ISSUE TITLE
没有公告的时候显示“暂无公告”的提示

### ISSUE THREAD

**Issue by SunnyCloudYang** [thu-info-community/thu-info-app#599]
**Is your feature request related to a problem? Please describe.**
没有公告的时候公告区会显示一个白框，是不是应该去掉或者显示“暂无公告”之类的提示文字？像预约那里的交互一样，让用户有明确的感知，不然我不知道是我的网不好没有加载出来还是真的没有公告。

**Describe the solution you'd like**
显示“暂无公告”或者不显示公告区域。

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by SunnyCloudYang** [comment]
AnnouncementSection 里看起来是没有公告就不显示，那应该是有公告但是解析出问题了？

**Comment by 84634E1A607A** [comment]
应该是有一些这个版本不需要显示的公告然后出了一些bug
