### ISSUE TITLE
课表能否支持隐藏周末

### ISSUE THREAD

**Issue by SunnyCloudYang** [thu-info-community/thu-info-app#619]
**Is your feature request related to a problem? Please describe.**
计划页面中，大多数同学周末没有课程，可以隐藏周末以充分利用课程表空间

**Describe the solution you'd like**
在计划页添加选项以隐藏周末

**Describe alternatives you've considered**
使用其他课程表软件。但是thuinfo不用导入和切换学期，如果能实现会比使用其他软件方便

**Additional context**
在新分支大概改了一下，不知道可不可行

**Comment by UNIDY2002** [comment]
可以发起 PR
