### ISSUE TITLE
UI相关问题

### ISSUE THREAD

**Issue by SunnyCloudYang** [thu-info-community/thu-info-app#628]
**Describe the solution you'd like**
1. [x] 底部tab离屏幕下边缘太近，考虑减小文字和图标间的距离，并为文字底部加上margin，保持总体高度不变；
2. [x] 主页公告栏的最小高度为92，看了代码但是没看出来小于这个值的副作用是什么，考虑减小或去除这一限制；
3. [x] 研究生收入的图标增加紫色区域，和整体更加协调；
4. [x] 电子发票view加圆角；
5. [x] 设置页面分割线可以看出是个框框；
6. [x] 课程界面隐藏计划的button不太统一，视觉提示也不够明显；
7. [x] 在线设备页按钮和外部圆角统一；
8. [x] 隐私页暗色模式失效，webview嵌套有些明显；
9. [x] 卫生成绩的图片背景始终是黑色
10. [x] refresh indicator始终是白色背景

暂时就发现这么多，都是很小的点就堆到一起提了，应该无伤大雅。等有时间了慢慢调整。

**Comment by 84634E1A607A** [comment]
8. 隐私页主要是给 APP Store 看的吧 (x), 这个页面没有做深色模式, 改不了

别的提的都挺好, 主要是懒 (x

**Comment by SunnyCloudYang** [comment]
> 8. 隐私页主要是给 APP Store 看的吧 (x), 这个页面没有做深色模式, 改不了

主要是晚上有时候不小心点到了就有点太亮了，我看之前也做了forcedark，但是好像不生效了，我琢磨一下怎么修

**Comment by SunnyCloudYang** [comment]
All done, closing
